// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZSTc0QNFzZGcAjiTrFeV_yJb1q3A0hsA',
    appId: '1:969551592231:web:5c547320f07733d2c10702',
    messagingSenderId: '969551592231',
    projectId: 'themeapp-2c2c8',
    authDomain: 'themeapp-2c2c8.firebaseapp.com',
    databaseURL: 'https://themeapp-2c2c8-default-rtdb.firebaseio.com',
    storageBucket: 'themeapp-2c2c8.firebasestorage.app',
    measurementId: 'G-RQH1S3HXZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9te7TJKBZEdfPkGOqJDjZ0D0LQR_ePTU',
    appId: '1:969551592231:android:7634e6d903880331c10702',
    messagingSenderId: '969551592231',
    projectId: 'themeapp-2c2c8',
    databaseURL: 'https://themeapp-2c2c8-default-rtdb.firebaseio.com',
    storageBucket: 'themeapp-2c2c8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZSTc0QNFzZGcAjiTrFeV_yJb1q3A0hsA',
    appId: '1:969551592231:web:4cab4fecc98bef6fc10702',
    messagingSenderId: '969551592231',
    projectId: 'themeapp-2c2c8',
    authDomain: 'themeapp-2c2c8.firebaseapp.com',
    databaseURL: 'https://themeapp-2c2c8-default-rtdb.firebaseio.com',
    storageBucket: 'themeapp-2c2c8.firebasestorage.app',
    measurementId: 'G-NLQQWXBK72',
  );
}
